### PR TITLE
Add SQLiteJournal

### PR DESCRIPTION
**Pull request by milo**
SQLiteJournal is derived from:
- https://github.com/nette/caching/blob/f07302949bed1cc7a1aa619d8ca0ec495a28a9c5/src/Caching/Storages/SqliteJournal.php
- https://github.com/nette/nette/commit/2ecbd51cfc6b050b6f7d88a382c4fe1a67913ac2
- https://github.com/nette/caching/blob/047db4858cf144783ca5d1c7f7dfccbf399bb4a2/src/Caching/Storages/SQLiteStorage.php

Are you @jsmitka and @dg ok with authority?

### CODE REVIEW

**Comment by dg** [comment]
:+1:

**Comment by dg** [comment]
(IMHO annotations @author are obsolete)

**Comment by chemix** [comment]
:+1:  idea for article why use SqlLite cache (speed test vs file) becase sqllite is possible use "everywhere" (redis not)

**Comment by dg** [comment]
This is not SQLite cache but SQLite journal. And it is slower than current default journal.

**Comment by chemix** [comment]
I need more read about it. Sorry.   I think Journal is cache with tags and others bonuses.

**Comment by dg** [comment]
Thank you!

**Comment by dg** [comment]
Now it is time to release nette/cache 2.4.0 :-)

**Comment by milo** [comment]
:+1: :o)

**Comment by JanTvrdik** [comment]
:+1: if you meant 2.4.0 RC1/beta1 and schedule 2.4 stable release in May or June.

**Comment by dg** [comment]
Yes, RC and schedule 2.4 stable in few weeks.

**Comment by dg** [comment]
ad 2.4: What about
- to change FileJournal -> SQLiteJournal in CacheExtension?
- to bump PHP version to 5.4?

- deprecation warnings in Cache should not be removed yet…
- 5.3 array syntax should be left yet too

**Comment by JanTvrdik** [comment]
:+1: Good plan!

**Comment by xificurk** [comment]
What's the point of PHP version bump, if the code should be left compatible with 5.3?

**Pull request merged**
